name: ci/cd
on:
  push:
    paths-ignore:
      - "**.md"
      - LICENCE
    branches:
      - main
  pull_request:
env:
  DEFAULT_GO_VERSION: 1.19
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: ${{ env.DEFAULT_GO_VERSION }}
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Run linter
        run: make lint
      - name: Run test
        run: make test